### ISSUE TITLE
Mod conflict with weird behavior

### ISSUE THREAD

**Issue by Mico27** [William758/ZetAspects#9]
Hi Im the creator of this mod https://github.com/Mico27/RoR2-TTGL-Mod and someone found a weird bug that occur on my survivor when they pick up a N'kuhana's Retort from your mod:

![image](https://user-images.githubusercontent.com/32064874/111017765-46fef300-8383-11eb-8583-a7fbbb204567.png)

Parts of the character (one of the characters head and hip specificaly) starts rotating when they pick up the item.
I was able to reproduce it with only my mod and yours installed.

However, I cannot seem to be able to find what exactly in your code what is causing this weird behavior.

**Comment by William758** [comment]
I believe this weird behavior is being caused by the base game.
Whenever a CharacterModel has the N'kuhana's skin applied, it causes the models head to twitch.
I'm not entirely sure how the game does this but CharacterModel.UpdatePoisonAffix uses JitterBones which should point you in the right direction.

**Comment by Mico27** [comment]
Ha thank you! I looked at UpdatePoisonAffix and JitterBones in dnSpy and it is indeed what was causing that weird effect. It also made me realize that I was using the wrong skinnedMeshRenderer for the main one that the JitterBones uses.
